<?php

declare(strict_types=1);

/**
 * AcceptanceTester — Generated actor class for E2E tests.
 *
 * This file is auto-generated by Codeception but is safe to add
 * custom helper methods to. Re-run `codecept build` if you add
 * new modules to codeception.yml.
 */
class AcceptanceTester extends \Codeception\Actor
{
    use _generated\AcceptanceTesterActions;

    /**
     * Fetches the most recent email from Mailpit and returns the first
     * magic link URL found in its HTML body.
     *
     * Throws if no email is found or no magic link is in the body.
     */
    public function grabMagicLinkFromLatestEmail(): string
    {
        // Give the mailer a moment to deliver
        $this->wait(1);

        $this->sendGet('/api/v1/messages');
        $this->seeResponseCodeIs(200);

        $body    = $this->grabResponse();
        $data    = json_decode($body, true);
        $msgId   = $data['messages'][0]['ID'] ?? null;

        \PHPUnit\Framework\Assert::assertNotNull($msgId, 'No emails found in Mailpit');

        $this->sendGet('/api/v1/message/' . $msgId);
        $html = json_decode($this->grabResponse(), true)['HTML'] ?? '';

        preg_match('/href="([^"]*verify\.php\?token=[^"]*)"/', $html, $m);
        \PHPUnit\Framework\Assert::assertNotEmpty($m[1] ?? '', 'No magic link found in email body');

        return html_entity_decode($m[1]);
    }

    /**
     * Deletes all messages from Mailpit — call this at the start of each test
     * so emails from previous tests don't interfere.
     */
    public function clearMailpit(): void
    {
        $this->sendDelete('/api/v1/messages');
    }
}
